"""
PDF Generator for CrewAI Article Output
Converts output_article.md to a styled PDF
"""

import os
import markdown2
from xhtml2pdf import pisa

# --- Read the markdown file ---
md_path = os.path.join(os.path.dirname(__file__), "output_article.md")
with open(md_path, "r", encoding="utf-8") as f:
    md_content = f.read()

# Strip the YAML frontmatter block (--- ... ---) and render it separately
lines = md_content.split("\n")
if lines[0].strip() == "---":
    end_idx = lines.index("---", 1)
    frontmatter_lines = lines[1:end_idx]
    body_md = "\n".join(lines[end_idx + 1:])
else:
    frontmatter_lines = []
    body_md = md_content

# Parse frontmatter into a dict
meta = {}
for line in frontmatter_lines:
    if ":" in line:
        key, _, val = line.partition(":")
        meta[key.strip()] = val.strip().strip('"')

# Convert markdown body to HTML
body_html = markdown2.markdown(
    body_md,
    extras=["tables", "fenced-code-blocks", "strike", "break-on-newline"]
)

# --- Build the full HTML document with embedded CSS ---
title = meta.get("title", "Article")
date  = meta.get("date", "")
read  = meta.get("reading_time", "")
tags  = meta.get("tags", "")
desc  = meta.get("description", "")

html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<style>
  @page {{
    size: A4;
    margin: 2.2cm 2.5cm 2.5cm 2.5cm;
    @frame footer {{
      -pdf-frame-content: footerContent;
      bottom: 1cm;
      height: 0.8cm;
    }}
  }}

  body {{
    font-family: Helvetica, Arial, sans-serif;
    font-size: 10.5pt;
    color: #1a1a1a;
    line-height: 1.65;
  }}

  /* ── Cover block ── */
  .cover {{
    background-color: #1a1a2e;
    color: #ffffff;
    padding: 28pt 24pt 22pt 24pt;
    margin-bottom: 20pt;
    border-radius: 4pt;
  }}
  .cover-title {{
    font-size: 19pt;
    font-weight: bold;
    color: #f0c040;
    line-height: 1.3;
    margin-bottom: 10pt;
  }}
  .cover-meta {{
    font-size: 8.5pt;
    color: #cccccc;
    margin-top: 4pt;
    line-height: 1.8;
  }}
  .cover-desc {{
    font-size: 9.5pt;
    color: #e0e0e0;
    margin-top: 10pt;
    font-style: italic;
  }}

  /* ── Headings ── */
  h1 {{
    font-size: 17pt;
    color: #1a1a2e;
    margin-top: 20pt;
    margin-bottom: 6pt;
    border-bottom: 2pt solid #f0c040;
    padding-bottom: 4pt;
  }}
  h2 {{
    font-size: 13pt;
    color: #1a1a2e;
    margin-top: 16pt;
    margin-bottom: 4pt;
    border-left: 4pt solid #f0c040;
    padding-left: 8pt;
  }}
  h3 {{
    font-size: 11pt;
    color: #333366;
    margin-top: 12pt;
    margin-bottom: 3pt;
  }}

  /* ── Body text ── */
  p {{
    margin-top: 0;
    margin-bottom: 8pt;
    text-align: justify;
  }}

  /* ── Blockquote (Editor's Note) ── */
  blockquote {{
    background-color: #fff8e7;
    border-left: 4pt solid #f0c040;
    margin: 10pt 0 12pt 0;
    padding: 8pt 12pt;
    font-size: 9.5pt;
    color: #555533;
    font-style: italic;
  }}
  blockquote p {{ margin-bottom: 0; }}

  /* ── Tables ── */
  table {{
    width: 100%;
    border-collapse: collapse;
    font-size: 9pt;
    margin: 10pt 0;
  }}
  th {{
    background-color: #1a1a2e;
    color: #f0c040;
    padding: 5pt 8pt;
    text-align: left;
    font-weight: bold;
  }}
  td {{
    padding: 4pt 8pt;
    border-bottom: 0.5pt solid #dddddd;
    vertical-align: top;
  }}
  tr:nth-child(even) td {{
    background-color: #f7f7f7;
  }}

  /* ── Horizontal rule ── */
  hr {{
    border: none;
    border-top: 1pt solid #cccccc;
    margin: 14pt 0;
  }}

  /* ── Inline code ── */
  code {{
    font-family: Courier, monospace;
    font-size: 9pt;
    background-color: #f0f0f0;
    padding: 1pt 3pt;
  }}

  /* ── Lists ── */
  ul, ol {{
    margin: 4pt 0 8pt 16pt;
    padding: 0;
  }}
  li {{
    margin-bottom: 3pt;
  }}

  /* ── Footer ── */
  #footerContent {{
    font-size: 7.5pt;
    color: #888888;
    text-align: center;
  }}
</style>
</head>
<body>

<!-- Cover / Metadata Block -->
<div class="cover">
  <div class="cover-title">{title}</div>
  <div class="cover-meta">
    Date: {date} &nbsp;|&nbsp; {read} &nbsp;|&nbsp; Tags: {tags}
  </div>
  <div class="cover-desc">{desc}</div>
</div>

<!-- Article Body -->
{body_html}

<!-- Footer -->
<div id="footerContent">
  Generated by CrewAI Multi-Agent System &nbsp;|&nbsp; Research → Writer → Editor → Publisher &nbsp;|&nbsp; {date}
</div>

</body>
</html>
"""

# --- Convert HTML → PDF ---
out_path = os.path.join(os.path.dirname(__file__), "output_article.pdf")

with open(out_path, "wb") as pdf_file:
    result = pisa.CreatePDF(html, dest=pdf_file, encoding="utf-8")

if result.err:
    print(f"ERROR: PDF generation failed with {result.err} error(s).")
else:
    size_kb = os.path.getsize(out_path) // 1024
    print(f"PDF created successfully: {out_path}  ({size_kb} KB)")
